### ISSUE TITLE
Runtime error: downcast of address 0x604000005850 which does not point to an object of type 'const IR::Input'

### ISSUE THREAD

**Issue by LebedevRI** [AliveToolkit/alive2#133]
```
$ ./alive /tmp/test.ll 
Processing /tmp/test.ll..

----------------------------------------
Name: shl (zext (i1 X)), C1 --> select (X, 1 << C1, 0)
  %Y = zext i1 %X to i32
  %Z = shl i32 %Y, C1
  ret i32 %Z
=>
  %tmp = shl i32 1, C1
  %Z = select i1 %X, i32 %tmp, 0
  ret %Z
  %Y = zext i1 %X to i32

../tools/transform.cpp:183:16: runtime error: downcast of address 0x604000005850 which does not point to an object of type 'const IR::Input'
0x604000005850: note: object is of type 'IR::ConstantInput'
 02 00 00 46  b0 5e 68 00 00 00 00 00  10 58 00 00 40 60 00 00  70 58 00 00 40 60 00 00  02 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'IR::ConstantInput'
    #0 0x655450 in preprocess(tools::Transform&, std::set<smt::expr, std::less<smt::expr>, std::allocator<smt::expr> > const&, std::set<smt::expr, std::less<smt::expr>, std::allocator<smt::expr> > const&, smt::expr&&) /repositories/alive2/build-Clang-default/../tools/transform.cpp:183:16
    #1 0x652bfa in check_refinement(util::Errors&, tools::Transform&, IR::State&, IR::State&, IR::Value const*, IR::Type const&, smt::expr const&, std::pair<IR::StateValue, std::set<smt::expr, std::less<smt::expr>, std::allocator<smt::expr> > > const&, smt::expr const&, std::pair<IR::StateValue, std::set<smt::expr, std::less<smt::expr>, std::allocator<smt::expr> > > const&, bool) /repositories/alive2/build-Clang-default/../tools/transform.cpp:266:28
    #2 0x651feb in tools::TransformVerify::verify() const /repositories/alive2/build-Clang-default/../tools/transform.cpp:327:7
    #3 0x4c7dcc in main /repositories/alive2/build-Clang-default/../tools/alive.cpp:124:30
    #4 0x7fcdf134ebba in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x26bba)
    #5 0x41bb19 in _start (/repositories/alive2/build-Clang-default/alive+0x41bb19)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../tools/transform.cpp:183:16 in 
Aborted

```

**Comment by nunoplopes** [comment]
Fixed, thanks!
