### ISSUE TITLE
ir/type.cpp:129:3: runtime error: execution reached an unreachable program point

### ISSUE THREAD

**Issue by LebedevRI** [AliveToolkit/alive2#67]
```
Name: zz
  %undef0 = udiv i8 %a, 0
  %X = uadd_overflow i8 %undef0, i8 %X
  %Y = extractvalue i8 %X, 0
  %Z = extractvalue i8 %X, 1
=>
  %undef0 = udiv i8 %a, 0
  %X = uadd_overflow i8 %undef0, i8 %X
  %Y = i8 0
  %Z = i1 false
```

```
$ ./alive -root-only /tmp/test.opt 
OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Processing /tmp/test.opt..

----------------------------------------
Name: zz
  %undef0 = udiv i8 %a, 0
  %X = uadd_overflow i8 %undef0, %X
  %Y = extractvalue i8 %X, 0
  %Z = extractvalue i8 %X, 1
=>
  %undef0 = udiv i8 %a, 0
  %X = uadd_overflow i8 %undef0, %X
  %Y = i8 0
  %Z = i1 0

../ir/type.cpp:129:3: runtime error: execution reached an unreachable program point
    #0 0x61a949 in IR::Type::getAsStructType() const /home/lebedevri/src/alive2/build-Clang-release/../ir/type.cpp:129:3
    #1 0x54b37b in IR::ExtractValue::getTypeConstraints(IR::Function const&) const /home/lebedevri/src/alive2/build-Clang-release/../ir/instr.cpp:581:21
    #2 0x4f9fa9 in IR::BasicBlock::getTypeConstraints(IR::Function const&) const /home/lebedevri/src/alive2/build-Clang-release/../ir/function.cpp:15:12
    #3 0x4fc019 in IR::Function::getTypeConstraints() const /home/lebedevri/src/alive2/build-Clang-release/../ir/function.cpp:53:14
    #4 0x688eca in tools::TransformVerify::getTypings() const /home/lebedevri/src/alive2/build-Clang-release/../tools/transform.cpp:314:18
    #5 0x44594a in main /home/lebedevri/src/alive2/build-Clang-release/../tools/alive.cpp:107:25
    #6 0x7fcda823409a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #7 0x39a029 in _start (/home/lebedevri/src/alive2/build-Clang-release/alive+0x39a029)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../ir/type.cpp:129:3 in 
Aborted
```

Should alive2 be added to oss-fuzz?

**Comment by nunoplopes** [comment]
thanks!
I think it's probably too early to fuzz it. We don't have bandwidth to fix all crashes.
